### ISSUE TITLE
Identifying someone as owner

### ISSUE THREAD

**Issue by fitnihil** [AllanGame/discord-moderator-bot#6]
Where do I apply an ID to set someone as owner?
Is it in the DB or in the code?

```json
{
    "owners": {
      "id": []
    }
  }
```

**Comment by AllanGame** [comment]
no, it is a list array, to add an item, in this perhaps your ID, you must put it inside "" like this:
```json
{
    "owners": {
      "id": ["YOUR-ID"]
    }
  }
```

for multiple:
```json
{
    "owners": {
      "id": ["YOUR-ID", "ANOTHER-OWNER-ID"]
    }
  }
```
