### ISSUE TITLE
onlyowner

### ISSUE THREAD

**Issue by HadesGitHub159** [AllanGame/discord-moderator-bot#8]
i'm trying to add a dev, but its not working, like i dont have access. and yes i have checked the data and misc .json and everything is working good, my id and everything.

**Comment by AllanGame** [comment]
In [misc.js](https://github.com/AllanGame/discord-moderator-bot/blob/development/src/utils/misc.json) file you must put your id inside "" like this:
```json
{
    "owners": {
      "id": ["YOUR-ID"]
    }
  }
```

for multiple:
```json
{
    "owners": {
      "id": ["YOUR-ID", "ANOTHER-OWNER-ID"]
    }
  }
```

If this doesnt work, it would be better if you show me some error in console

**Comment by HadesGitHub159** [comment]
{
    "owners": {
      "id": []
    }
  }
